DROP DATABASE IF EXISTS socially CASCADE;
CREATE DATABASE IF NOT EXISTS socially;
SET DATABASE = socially;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL NOT NULL PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    username VARCHAR NOT NULL UNIQUE
);